AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WriteFileMeta:
    Properties:
      CodeUri: s3://codes-pc-connect/d0b4053fcb730ef6af6e25bc5b6d6352
      Environment:
        Variables:
          S3_BUCKET: madori-web
          STAGE: prod
          TABLE_NAME: madori_files
          TZ: Asia/Tokyo
      FunctionName: WriteFileMeta
      Handler: index.handler
      Role: arn:aws:iam::032500022239:role/sam_role
      Runtime: nodejs8.10
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
