AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  GetDownloadUrl:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 60
      FunctionName: GetDownloadUrl
      CodeUri: src
      Role: arn:aws:iam::004590054840:role/madori_lambda_role
      Environment :
        Variables:
          BUCKET_NAME: madori-cloud-user-storage-test
          TZ: Asia/Tokyo
