AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs8.10
    Timeout: 60
Outputs:
  CheckCapacityOutput:
    Description: CheckCapacity
    Export:
      Name: CheckCapacity
    Value:
      Ref: CheckCapacity
  CreatePresigndUrlOutput:
    Description: CreatePresigndUrl
    Export:
      Name: CreatePresigndUrl
    Value:
      Ref: CreatePresigndUrl
  CreateUploadUrlOutput:
    Description: CreateUploadUrl
    Export:
      Name: CreateUploadUrl
    Value:
      Ref: CreateUploadUrl
  DeleteFilesOutput:
    Description: DeleteFiles
    Export:
      Name: DeleteFiles
    Value:
      Ref: DeleteFiles
  GetDownloadUrlOutput:
    Description: GetDownloadUrl
    Export:
      Name: GetDownloadUrl
    Value:
      Ref: GetDownloadUrl
  GetTokenOutput:
    Description: GetToken
    Export:
      Name: GetToken
    Value:
      Ref: GetToken
  GetUsersOutput:
    Description: GetUsers
    Export:
      Name: GetUsers
    Value:
      Ref: GetUsers
  MadoriApiOutput:
    Description: MadoriApi
    Export:
      Name: MadoriApi
    Value:
      Ref: MadoriApi
  RefleshTokenOutput:
    Description: RefleshToken
    Export:
      Name: RefleshToken
    Value:
      Ref: RefleshToken
  S3CreateEventOutput:
    Description: S3CreateEvent
    Export:
      Name: S3CreateEvent
    Value:
      Ref: S3CreateEvent
  SearchFilesOutput:
    Description: SearchFiles
    Export:
      Name: SearchFiles
    Value:
      Ref: SearchFiles
  SignInOutput:
    Description: SignIn
    Export:
      Name: SignIn
    Value:
      Ref: SignIn
Parameters:
  LambdaArn:
    Default: arn:aws:iam::004590054840:role/madori_lambda_role
    Type: String
  StageParam:
    Default: test
    Type: String
Resources:
  CheckCapacity:
    Properties:
      CodeUri: s3://madori-cloud-code/b0bf05feb5d4e6f5f16bec53fbb956bd
      Environment:
        Variables:
          BUCKET_NAME: madori-cloud-user-storage
          CAPACITY_SETTING_FILE_KEY: v1/capacity.json
          SETTING_BUCKET: madori-cloud-settings
          TZ: Asia/Tokyo
          USER_POOL_ID: ap-northeast-1_mV33Mv9Co
          WARNING_LIMIT: 0.9
      FunctionName: CheckCapacity
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
  CloudwatchRoleSetting:
    Properties:
      CloudWatchRoleArn: arn:aws:iam::004590054840:role/apigateway_cloudwatchlogs_role
    Type: AWS::ApiGateway::Account
  CreatePresigndUrl:
    Properties:
      CodeUri: s3://madori-cloud-code/869924a87d831ca725dd185ad47179d4
      Environment:
        Variables:
          CLOUDFRONT_KEY_PAIR_ID: APKAJMDZLPPBMFR5I3WQ
          DOMAIN: madori.cloud
          PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAjVehWH7yHzdWl51dYt8urw6EGoG1V4RJqmoatV8rBkfioJBZ\nXoWoVAPWlsqtzemX4Oz/MQPZvEfAG5mQO/LNENKsDg+9G1E3xi4dMvlU5jsbnVQW\nbqYytxvffq2nUnmndGoX2AXQrCujXwJfMKY12x5NgRc4aOG5PcO4zmG+nROEbwD8\n0YOlIo7/m/LWrzzY+tp0xICiJVamcpDnY8xPNFkYxYC/uMujjMBYz5pmTC5tIfIW\nRfzWpOfarT9Qz1/t5FF7W3tS5hD9q0yZPF3R858VPgdqGjpPgZNKuG4UYNM4/hFs\niygV3qYer0ptoF6FPxg/V2eR9vsktHEiSd/LJwIDAQABAoIBAA+glrhAIOkOp0ZQ\nIdkir/iu9DAyEyi/+Z0b6iQPh6REImx6SUdII9pWKk21zw2rPB2kVnrG4DYPANCM\nZAQczkuD334Wg2QX0MDarGPMaXSjKGR2vZwyR/0y2b0Z2hwmUztt14EM84t1r7R7\ngKbSWbYGXa9eL+B4xJBtqWs4J2kaaXzKUMumIzyL60IH52Fq8tskMwKyQKW1xicu\nl6vQBLoBjUTbzJT/0aF72+udwic0Ch0Ubp6yihH2EpaY4c3FbUGG1iBUoIZPoCtL\nNtcwRRxaUvgIFTb3VHlMpzGTkQ1QsySU/V2xLdnh2lIo8GseqF3JttNAtJgdG5wF\nysAzPnECgYEA/iP5YxHCQXEdonBds7bpA/i0GiJCsTACHXa5RJLvCz9ew9X6t54S\ng2C92RHolvHocIseo6r+XA7D4oxpcCSm5V/RIIr9KAfm/Ku5sGwyXrYkEYyTDZiL\nRoSTRWNtE4u7ICc7n8ttmmXr7baEtmEfGPMddiZB0gBqcrWoNtyM1/UCgYEAjmBg\nOPJQldZbZUxBx2tHdPqNTMC46YpWKkQZ0GCGwkuq3YGcKvtoIJ7ZiZTLQW8cdoIa\neKRr51Bk9OzHKo3HjYk7eUxVJ5WXXjyTL/QGjiO1r5h5ebj9svklB3GYH0Fslv35\n1ovqZ9yCXOvwO4UXltFz8hHcn1wvMdltUT93USsCgYEA3dmViJAmHW6bSgQBKDLR\n8q+WuQGTao3YKtRLIruJhS4KkbYnqUaKLrmywN1LRwlhuW0YkBNi/AW/pfKg0E6O\nisk8C8aI+/r5/zQBYyrwRZGGpvMqI8I4QpTU4svKmjduYMEe4X157kBu1hJwg60A\nsoz3+P2ok6PdSMmfUFTzdkkCgYArZaTutq1pfpUNI1lJd6GoPlajdnrmdIwfBfL4\nWPO6dWX3bnIzh74Nc13LWdc6cquyU6XN8BATyaV8Ik/y4JRax+Gg72tlTWt+Bei3\nTSJSYQAYLdmZCJIL43Ut96nunPqEa5Wjl7IzRjtWJ3RqL/8osV8uAdPFn0ujXiq8\nASRVUQKBgQDJ/SJs/B9kXsE3jAnSTL6tzziA7Dx71ziQlV8M6rhLAf7G7kekU5qO\n6FWyjr37BNbbW8F4/YJFF/oQCd3H/VpOQSaYPNdgHErk/9sephrCO/hjdeRMh1kB\nTbqaYxY6zRj15zdXLP2JWp53iH8o56eAEyldRRqGjB+HHFJTqCW2aw==\n-----END
            RSA PRIVATE KEY-----'
          PUBLIC_KEY: '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjVehWH7yHzdWl51dYt8u\nrw6EGoG1V4RJqmoatV8rBkfioJBZXoWoVAPWlsqtzemX4Oz/MQPZvEfAG5mQO/LN\nENKsDg+9G1E3xi4dMvlU5jsbnVQWbqYytxvffq2nUnmndGoX2AXQrCujXwJfMKY1\n2x5NgRc4aOG5PcO4zmG+nROEbwD80YOlIo7/m/LWrzzY+tp0xICiJVamcpDnY8xP\nNFkYxYC/uMujjMBYz5pmTC5tIfIWRfzWpOfarT9Qz1/t5FF7W3tS5hD9q0yZPF3R\n858VPgdqGjpPgZNKuG4UYNM4/hFsiygV3qYer0ptoF6FPxg/V2eR9vsktHEiSd/L\nJwIDAQAB\n-----END
            PUBLIC KEY-----\n'
          ROOT_PAGE: storage/index.html
          TZ: Asia/Tokyo
      FunctionName: CreatePresigndUrl
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
  CreateUploadUrl:
    Properties:
      CodeUri: s3://madori-cloud-code/055d6995558eb4363ee19fd6a497f285
      Environment:
        Variables:
          REPLACEMENT_FILE_KEY: v1/replacement.json
          S3_BUCKET: madori-cloud-user-storage
          SETTING_BUCKET: madori-cloud-settings
          TZ: Asia/Tokyo
      FunctionName: CreateUploadUrl
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
  DeleteFiles:
    Properties:
      CodeUri: s3://madori-cloud-code/548e448a97127c4231afe0cd8e1fba52
      Environment:
        Variables:
          MADORIDATA_BUCKET_NAME: madori-cloud-user-storage
          TABLE_NAME: madori-files
          THUMBNAIL_BUCKET_NAME: madori-cloud-system-storage
          TZ: Asia/Tokyo
      FunctionName: DeleteFiles
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
  GetDownloadUrl:
    Properties:
      CodeUri: s3://madori-cloud-code/6eef3b2675d1345a2eb1a5a0f7d051b0
      Environment:
        Variables:
          BUCKET_NAME: madori-cloud-user-storage
          TZ: Asia/Tokyo
      FunctionName: GetDownloadUrl
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
  GetToken:
    Properties:
      CodeUri: s3://madori-cloud-code/5d28952bfdb79744af41cf702ecea60e
      Environment:
        Variables:
          CLIENT_ID: pk63mpl440cll91sqnjjk6oa3
          PASS_KEY: madori
          TZ: Asia/Tokyo
          USER_POOL_ID: ap-northeast-1_mV33Mv9Co
      FunctionName: GetToken
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
  GetUsers:
    Properties:
      CodeUri: s3://madori-cloud-code/e49793eb2710a3bc121e7f3ce103d3cf
      Environment:
        Variables:
          BUCKET_NAME: madori-cloud-user-storage
          TZ: Asia/Tokyo
      FunctionName: GetUsers
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
  MadoriApi:
    Properties:
      BodyS3Location:
        Bucket: madori-cloud-code
        Key: v1/swagger.yml
      Name: madori
      Parameters:
        String: String
    Type: AWS::ApiGateway::RestApi
  MadoriBucket:
    Properties:
      BucketName: madori-cloud-user-storage-test
    Type: AWS::S3::Bucket
  RefleshToken:
    Properties:
      CodeUri: s3://madori-cloud-code/3ff1e663bc7b8bdc53ab51babefb9dd7
      Environment:
        Variables:
          CLIENT_ID: pk63mpl440cll91sqnjjk6oa3
          TZ: Asia/Tokyo
          USER_POOL_ID: ap-northeast-1_mV33Mv9Co
          WEB_AUTH_URL: https://kanri.madori.co.jp/auth/auth.php
      FunctionName: RefleshToken
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
  S3CreateEvent:
    Properties:
      CodeUri: s3://madori-cloud-code/af070f011e673ebdfefaf6c4b52d364b
      Environment:
        Variables:
          MADORI_BUCKET: madori-cloud-user-storage
          TABLE_NAME: madori-files
          THUMBNAIL_BUCKET: madori-cloud-system-storage
          THUMBNAIL_FILE_NAME: zumen.jpg
          TZ: Asia/Tokyo
      FunctionName: S3CreateEvent
      MemorySize: 512
      Role:
        Ref: LambdaArn
      Timeout: 120
    Type: AWS::Serverless::Function
  S3CreateEventTest:
    Properties:
      CodeUri: s3://madori-cloud-code/af070f011e673ebdfefaf6c4b52d364b
      Environment:
        Variables:
          MADORI_BUCKET: madori-cloud-user-storage-test
          TABLE_NAME: madori-files-test2
          THUMBNAIL_BUCKET: madori-cloud-system-storage-test
          THUMBNAIL_FILE_NAME: zumen.jpg
          TZ: Asia/Tokyo
      FunctionName: S3CreateEventTest
      MemorySize: 512
      Role:
        Ref: LambdaArn
      Timeout: 120
    Type: AWS::Serverless::Function
  SearchFiles:
    Properties:
      CodeUri: s3://madori-cloud-code/88f11f3b23f88e18609fc2603416b718
      Environment:
        Variables:
          FILENAME_INDEX: filename-index
          LATEST_INDEX: latest-index
          SIZE_INDEX: size-index
          TABLE_NAME: madori-files
          TZ: Asia/Tokyo
          USERNAME_INDEX: username-index
      FunctionName: SearchFiles
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
  SignIn:
    Properties:
      CodeUri: s3://madori-cloud-code/80a67b477b095186cd004e95d72cfc86
      Environment:
        Variables:
          CLIENT_ID: pk63mpl440cll91sqnjjk6oa3
          KEY_ID: 0022d1d9-f0c7-45e1-8f84-2b77c6fdcba9
          PASS_KEY: madori
          TZ: Asia/Tokyo
          USER_POOL_ID: ap-northeast-1_mV33Mv9Co
          WEB_AUTH_URL: https://kanri.madori.co.jp/auth/auth.php
      FunctionName: SignIn
      Role:
        Ref: LambdaArn
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
