AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs8.10
    Timeout: 15
Parameters:
  LambdaArn:
    Default: arn:aws:iam::032500022239:role/sam_role
    Type: String
  StageParam:
    Default: test
    Type: String
Resources:
  CheckCapacity:
    Properties:
      AutoPublishAlias:
        Ref: StageParam
      CodeUri: s3://codes-pc-connect/ab640c5387eabcdd1fed2572049b031f
      Environment:
        Variables:
          BASIC_CAPACITY: 10B
          BUCKET_NAME: madori-web
          BUSINESS_CAPACITY: 2.3MB
          TZ: Asia/Tokyo
          USER_POOL_ID: ap-northeast-1_srHUAjtc2
          WARNING_LIMIT: 0.9
      Events:
        Api:
          Properties:
            Method: get
            Path: /storage/status
            RestApiId:
              Ref: MadoriApi
          Type: Api
      FunctionName: CheckCapacity
      Role: arn:aws:iam::032500022239:role/sam_role
    Type: AWS::Serverless::Function
  CreatePresigndUrl:
    Properties:
      AutoPublishAlias:
        Ref: StageParam
      CodeUri: s3://codes-pc-connect/422a9c4b88a0fc1579c4d45584684be9
      Environment:
        Variables:
          S3_BUCKET: madori-web
          TABLE_NAME: madori_files
          TZ: Asia/Tokyo
      Events:
        Api:
          Properties:
            Method: get
            Path: /settings/url
            RestApiId:
              Ref: MadoriApi
          Type: Api
      FunctionName: CreatePresigndUrl
      Role: arn:aws:iam::032500022239:role/sam_role
    Type: AWS::Serverless::Function
  CreateUploadUrl:
    Properties:
      AutoPublishAlias:
        Ref: StageParam
      CodeUri: s3://codes-pc-connect/91a7315a7a58a6d49c9d28e26cddd5f3
      Environment:
        Variables:
          S3_BUCKET: madori_web
          TZ: Asia/Tokyo
      Events:
        Api:
          Properties:
            Method: get
            Path: /upload/url
            RestApiId:
              Ref: MadoriApi
          Type: Api
      FunctionName: CreateUploadUrl
      Role: arn:aws:iam::032500022239:role/sam_role
    Type: AWS::Serverless::Function
  MadoriApi:
    Properties:
      DefinitionUri: s3://codes-pc-connect/3368d2b5175811f37dd64682eb546197
      MethodSettings:
      - DataTraceEnabled: true
        HttpMethod: '*'
        LoggingLevel: ERROR
        ResourcePath: /*
      Name: madori-test
      StageName:
        Ref: StageParam
      Variables:
        Stage:
          Ref: StageParam
    Type: AWS::Serverless::Api
  MadoriBucket:
    Properties:
      BucketName: cf-test-madori
    Type: AWS::S3::Bucket
  RefleshToken:
    Properties:
      AutoPublishAlias:
        Ref: StageParam
      CodeUri: s3://codes-pc-connect/cce06b624fb313a1df43adb71ee666bb
      Environment:
        Variables:
          ACCESS_KEY: AKIAJCHRBIHIOWKD5U4A
          CLIENT_ID: 14hg9uas2k1dlffrr9ot02pvkt
          KEY_ID: 93bc2dde-6218-4d49-a700-6f17f4b275da
          SECRET_KEY: VL+5B72Z2aj9rz8Wj5Hv6E9wGh8rTz0hR9s18r6Q
          STAGE: prod
          TZ: Asia/Tokyo
          USER_POOL_ID: ap-northeast-1_srHUAjtc2
          WEB_AUTH_URL: https://kanri.madori.co.jp/auth/auth.php
      Events:
        Api:
          Properties:
            Method: get
            Path: /auth/reflesh
            RestApiId:
              Ref: MadoriApi
          Type: Api
      FunctionName: RefleshToken
      Role: arn:aws:iam::032500022239:role/sam_role
    Type: AWS::Serverless::Function
  S3CreateEvent:
    Properties:
      CodeUri: s3://codes-pc-connect/4cdf3c30d1e1ac6848b1bd5848b05011
      Environment:
        Variables:
          MADORI_BUCKET: madori-web
          STAGE: prod
          TABLE_NAME: madori_files
          THUMBNAIL_BUCKET: madori-web
          THUMBNAIL_FILE_NAME: zumen.jpg
          TZ: Asia/Tokyo
      Events:
        S3Put:
          Properties:
            Bucket:
              Ref: MadoriBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .mdzx
          Type: S3
      FunctionName: S3CreateEvent
      Role: arn:aws:iam::032500022239:role/sam_role
    Type: AWS::Serverless::Function
  S3DeleteEvent:
    Properties:
      CodeUri: s3://codes-pc-connect/bd36c323d80ffe3858ef25d903f7be09
      Environment:
        Variables:
          S3_BUCKET: madori-web
          STAGE: prod
          TABLE_NAME: madori_files
          TZ: Asia/Tokyo
      Events:
        S3Put:
          Properties:
            Bucket:
              Ref: MadoriBucket
            Events: s3:ObjectRemoved:*
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .mdzx
          Type: S3
      FunctionName: S3DeleteEvent
      Role: arn:aws:iam::032500022239:role/sam_role
    Type: AWS::Serverless::Function
  SignIn:
    Properties:
      AutoPublishAlias:
        Ref: StageParam
      CodeUri: s3://codes-pc-connect/83ac9276083723847215011cc370692e
      Environment:
        Variables:
          CLIENT_ID: 14hg9uas2k1dlffrr9ot02pvkt
          KEY_ID: 93bc2dde-6218-4d49-a700-6f17f4b275da
          PASS_KEY: madori
          TZ: Asia/Tokyo
          USER_POOL_ID: ap-northeast-1_srHUAjtc2
          WEB_AUTH_URL: https://jnvdhrd7f0.execute-api.ap-northeast-1.amazonaws.com/prod/web-auth-test
      Events:
        Api:
          Properties:
            Method: post
            Path: /auth/login
            RestApiId:
              Ref: MadoriApi
          Type: Api
      FunctionName: SignIn
      Role: arn:aws:iam::032500022239:role/sam_role
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
