AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  LambdaVersionTest:
    Description: LambdaVersionTest
    Export:
      Name: LambdaVersionTest
    Value:
      Ref: LambdaVersionTest
Parameters:
  LambdaArn:
    Default: arn:aws:iam::004590054840:role/madori_lambda_role
    Type: String
  PublishVersionArn:
    Default: arn:aws:lambda:ap-northeast-1:004590054840:function:PublishLambdaVersion
    Type: String
  StageParam:
    Default: test
    Type: String
Resources:
  LambdaVersionTest:
    Properties:
      CodeUri: s3://madori-cloud-code/b0bf05feb5d4e6f5f16bec53fbb956bd
      Environment:
        Variables:
          BUCKET_NAME: madori-cloud-user-storage-test
          CAPACITY_SETTING_FILE_KEY: test/capacity.json
          SETTING_BUCKET: madori-cloud-settings
          TZ: Asia/Tokyo
          USER_POOL_ID: ap-northeast-1_rGf8HWsVW
          WARNING_LIMIT: 0.9
      FunctionName: LambdaVersionTest2
      Handler: index.handler
      Role:
        Ref: LambdaArn
      Runtime: nodejs8.10
      Timeout: 60
    Type: AWS::Serverless::Function
  LambdaVersionTestPermission:
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - LambdaVersionTestPublish
        - AliasArn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub:
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayApi}/${StageParam}/*/*
        - ApiGatewayApi:
            Fn::ImportValue: MadoriApi
    Type: AWS::Lambda::Permission
  LambdaVersionTestPublish:
    Metadata:
      PublishDate: aaaaaaaaa
    Properties:
      Alias:
        Ref: StageParam
      FunctionName:
        Ref: LambdaVersionTest
      ServiceToken:
        Ref: PublishVersionArn
    Type: Custom::PublishVersion
Transform: AWS::Serverless-2016-10-31
