AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LambdaArn:
    Default: arn:aws:iam::004590054840:role/madori_lambda_role
    Type: String
  PublishId:
    Default: 2
    Type: String
  PublishVersionArn:
    Default: arn:aws:lambda:ap-northeast-1:004590054840:function:PublishLambdaVersion
    Type: String
  StageParam:
    Default: test
    Type: String
Resources:
  LambdaVersionTestPermission:
    DependsOn: LambdaVersionTestPublish
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - LambdaVersionTestPublish
        - AliasArn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub:
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayApi}/${StageParam}/*/*
        - ApiGatewayApi:
            Fn::ImportValue: MadoriApi
    Type: AWS::Lambda::Permission
  LambdaVersionTestPublish:
    Properties:
      Alias:
        Ref: StageParam
      FunctionName: LambdaVersionTest2
      PublishId:
        Ref: PublishId
      ServiceToken:
        Ref: PublishVersionArn
    Type: Custom::PublishVersion
Transform: AWS::Serverless-2016-10-31
