AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters: 
    StageParam: 
      Type: String
      Default: test
Resources:

  CreatePresigndUrl:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 60
      FunctionName: CreatePresigndUrl
      CodeUri: src
      Role: arn:aws:iam::032500022239:role/sam_role
      Environment :
        Variables:
          PUBLIC_KEY: -----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjVehWH7yHzdWl51dYt8u\nrw6EGoG1V4RJqmoatV8rBkfioJBZXoWoVAPWlsqtzemX4Oz/MQPZvEfAG5mQO/LN\nENKsDg+9G1E3xi4dMvlU5jsbnVQWbqYytxvffq2nUnmndGoX2AXQrCujXwJfMKY1\n2x5NgRc4aOG5PcO4zmG+nROEbwD80YOlIo7/m/LWrzzY+tp0xICiJVamcpDnY8xP\nNFkYxYC/uMujjMBYz5pmTC5tIfIWRfzWpOfarT9Qz1/t5FF7W3tS5hD9q0yZPF3R\n858VPgdqGjpPgZNKuG4UYNM4/hFsiygV3qYer0ptoF6FPxg/V2eR9vsktHEiSd/L\nJwIDAQAB\n-----END PUBLIC KEY-----\n
          PRIVATE_KEY: -----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAjVehWH7yHzdWl51dYt8urw6EGoG1V4RJqmoatV8rBkfioJBZ\nXoWoVAPWlsqtzemX4Oz/MQPZvEfAG5mQO/LNENKsDg+9G1E3xi4dMvlU5jsbnVQW\nbqYytxvffq2nUnmndGoX2AXQrCujXwJfMKY12x5NgRc4aOG5PcO4zmG+nROEbwD8\n0YOlIo7/m/LWrzzY+tp0xICiJVamcpDnY8xPNFkYxYC/uMujjMBYz5pmTC5tIfIW\nRfzWpOfarT9Qz1/t5FF7W3tS5hD9q0yZPF3R858VPgdqGjpPgZNKuG4UYNM4/hFs\niygV3qYer0ptoF6FPxg/V2eR9vsktHEiSd/LJwIDAQABAoIBAA+glrhAIOkOp0ZQ\nIdkir/iu9DAyEyi/+Z0b6iQPh6REImx6SUdII9pWKk21zw2rPB2kVnrG4DYPANCM\nZAQczkuD334Wg2QX0MDarGPMaXSjKGR2vZwyR/0y2b0Z2hwmUztt14EM84t1r7R7\ngKbSWbYGXa9eL+B4xJBtqWs4J2kaaXzKUMumIzyL60IH52Fq8tskMwKyQKW1xicu\nl6vQBLoBjUTbzJT/0aF72+udwic0Ch0Ubp6yihH2EpaY4c3FbUGG1iBUoIZPoCtL\nNtcwRRxaUvgIFTb3VHlMpzGTkQ1QsySU/V2xLdnh2lIo8GseqF3JttNAtJgdG5wF\nysAzPnECgYEA/iP5YxHCQXEdonBds7bpA/i0GiJCsTACHXa5RJLvCz9ew9X6t54S\ng2C92RHolvHocIseo6r+XA7D4oxpcCSm5V/RIIr9KAfm/Ku5sGwyXrYkEYyTDZiL\nRoSTRWNtE4u7ICc7n8ttmmXr7baEtmEfGPMddiZB0gBqcrWoNtyM1/UCgYEAjmBg\nOPJQldZbZUxBx2tHdPqNTMC46YpWKkQZ0GCGwkuq3YGcKvtoIJ7ZiZTLQW8cdoIa\neKRr51Bk9OzHKo3HjYk7eUxVJ5WXXjyTL/QGjiO1r5h5ebj9svklB3GYH0Fslv35\n1ovqZ9yCXOvwO4UXltFz8hHcn1wvMdltUT93USsCgYEA3dmViJAmHW6bSgQBKDLR\n8q+WuQGTao3YKtRLIruJhS4KkbYnqUaKLrmywN1LRwlhuW0YkBNi/AW/pfKg0E6O\nisk8C8aI+/r5/zQBYyrwRZGGpvMqI8I4QpTU4svKmjduYMEe4X157kBu1hJwg60A\nsoz3+P2ok6PdSMmfUFTzdkkCgYArZaTutq1pfpUNI1lJd6GoPlajdnrmdIwfBfL4\nWPO6dWX3bnIzh74Nc13LWdc6cquyU6XN8BATyaV8Ik/y4JRax+Gg72tlTWt+Bei3\nTSJSYQAYLdmZCJIL43Ut96nunPqEa5Wjl7IzRjtWJ3RqL/8osV8uAdPFn0ujXiq8\nASRVUQKBgQDJ/SJs/B9kXsE3jAnSTL6tzziA7Dx71ziQlV8M6rhLAf7G7kekU5qO\n6FWyjr37BNbbW8F4/YJFF/oQCd3H/VpOQSaYPNdgHErk/9sephrCO/hjdeRMh1kB\nTbqaYxY6zRj15zdXLP2JWp53iH8o56eAEyldRRqGjB+HHFJTqCW2aw==\n-----END RSA PRIVATE KEY-----
          CLOUDFRONT_KEY_PAIR_ID: APKAJMDZLPPBMFR5I3WQ
          DOMAIN: madori.cloud
          ROOT_PAGE: test/storage/index.html
          STAGE: prod
          TZ: Asia/Tokyo

