AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters: 
    StageParam: 
      Type: String
      Default: test
Resources:

  CreatePresigndUrl:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 15
      FunctionName: CreatePresigndUrl
      CodeUri: src
      Role: arn:aws:iam::032500022239:role/sam_role
      Environment :
        Variables:
          S3_BUCKET: madori.cloud
          SETTING_PAGE_PATH: dest/index.html
          STAGE: prod
          TZ: Asia/Tokyo

