AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  StageParam:
    Default: test
    Type: String
Resources:
  CheckCapacityApi:
    Properties:
      DefinitionUri: s3://codes-pc-connect/383e0385181a1fba473503dd5a4975c5
      MethodSettings:
      - DataTraceEnabled: true
        HttpMethod: '*'
        LoggingLevel: ERROR
        ResourcePath: /*
      Name: madori-test
      StageName:
        Ref: StageParam
      Variables:
        Stage:
          Ref: StageParam
    Type: AWS::Serverless::Api
  CreatePresigndUrl:
    Properties:
      CodeUri: s3://codes-pc-connect/422a9c4b88a0fc1579c4d45584684be9
      Environment:
        Variables:
          S3_BUCKET: madori-web
          STAGE: prod
          TABLE_NAME: madori_files
          TZ: Asia/Tokyo
      Events:
        Api:
          Properties:
            Method: get
            Path: /upload/url
            RestApiId:
              Ref: CheckCapacityApi
          Type: Api
      FunctionName: CreatePresigndUrl
      Handler: index.handler
      Role: arn:aws:iam::032500022239:role/sam_role
      Runtime: nodejs8.10
      Timeout: 15
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
